version: '3'
services:
  build:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: build
  prod:
    build:
      context: ./prod
      dockerfile: Dockerfile
    image: prod
    ports:
      - "8080:8080"
    depends_on:
      - build