version: '3.8'
services:
  app-build:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: app-build
  app-run:
    build:
      context: ./prod
      dockerfile: Dockerfile
    container_name: prod
    depends_on:
      - app-build
    ports:
      - "8087:8080"