version: '3.8'
services:
  app-build:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: app-build
    volumes:
      - ./tomcat-webapps:/opt/tomcat/webapps/
volumes:
  tomcat-webapps: