version: '3'
services:
  build:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: build
    volumes:
      - app-data:/opt/tomcat/webapps
  prod:
    build:
      context: ./prod
      dockerfile: Dockerfile
    image: prod
    ports:
      - "8095:8080"
    depends_on:
      - build
    volumes:
      - app-data:/usr/local/tomcat/webapps
volumes:
  app-data: {}